server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8091
  servlet:
    context-path: /

spring:
  #MySQL???
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/smartcall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      #password: 708708Aa
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  # Redis 核心配置
  redis:
    # 服务器地址（单机版），集群/哨兵需单独配置
    host: 127.0.0.1
    # Redis 端口，默认6379
    port: 6379
    # 密码（无密码则注释或留空）
    password: QWER1234
    # 数据库索引（Redis默认有16个库，0-15，建议单独用一个库区分业务）
    database: 0





